# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 01:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('level', models.IntegerField(default=1)),
                ('xp', models.IntegerField(default=0)),
                ('ataque', models.IntegerField(default=10)),
                ('defese', models.IntegerField(default=10)),
                ('genre', models.IntegerField(default=1)),
                ('creat_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
