# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 05:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('level', models.IntegerField()),
                ('xp', models.IntegerField()),
                ('ataque', models.IntegerField()),
                ('defese', models.IntegerField()),
                ('creat_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
